# Generated by Django 4.0.1 on 2022-01-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='account',
        ),
    ]
